### ISSUE TITLE
⛺️第2期第7题：圆？半圆？椭圆？

### ISSUE THREAD

**Issue by LinDaiDai** [LinDaiDai/niubility-coding-js#14]
### 圆？半圆？椭圆？

```css
div {
  width: 100px;
  height: 100px;
  background-color: red;
  margin-top: 20px;
}
.box1 { /* 圆 */
  /* border-radius: 50%; */
  border-radius: 50px;
}
.box2 { /* 半圆 */
  height: 50px;
  border-radius: 50px 50px 0 0;
}
.box3 { /* 椭圆 */
  height: 50px;
  border-radius: 50px/25px; /* x轴/y轴 */
}
```
