### ISSUE TITLE
🍃第1期第6题：文字单超出显示省略号

### ISSUE THREAD

**Issue by LinDaiDai** [LinDaiDai/niubility-coding-js#6]
### 文字单超出显示省略号

```css
div {
  width: 200px;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
```
